name: Build and Push Base Image

on:
  workflow_dispatch:
    inputs: 
      aws_region:
        description: 'AWS Region to deploy to'
        required: true
        default: 'us-east-1'
        type: string

env:
  AWS_REGION: ${{ github.event.inputs.aws_region }}
  
jobs:
  build-and-push-base:
    name: Build and push base image
    # needs: [validate-inputs] # Removed because the job is commented out
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - id: image-build
        name: Build container image
        env:
          LOCAL_IMAGE_REPOSITORY: ${{ github.event.repository.name }}
        run: |
          docker build \
            -f app/Dockerfile \
            --label git-commit='${{ github.sha }}' \
            --tag $LOCAL_IMAGE_REPOSITORY:baseimage \
            .
          echo "## Image build" >> $GITHUB_STEP_SUMMARY
          echo "- Build succeeded" >> $GITHUB_STEP_SUMMARY

      - id: credentials-image-push
        name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - id: login-ecr-push
        name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - id: image-tag-push
        name: Tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr-push.outputs.registry }}
          ECR_REPOSITORY: ${{ github.event.repository.name }}
          LOCAL_IMAGE_REPOSITORY: ${{ github.event.repository.name }}
        run: |
          IMAGE_URL="$ECR_REGISTRY/$ECR_REPOSITORY:baseimage"
          docker tag $LOCAL_IMAGE_REPOSITORY:baseimage $IMAGE_URL
          docker push $IMAGE_URL
          
          # This sets the value for the job output
          echo "image_url=$IMAGE_URL" >> $GITHUB_OUTPUT
          echo "- Pushed to ECR: **$IMAGE_URL**" >> $GITHUB_STEP_SUMMARY

    # Reference the step ID 'image-tag-push' and the output name 'image_url'
    outputs:
      image_url: ${{ steps.image-tag-push.outputs.image_url }}